name: Continuous Delivery

on:
  push:
    branches:
      - main
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Changes and Release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.printoutputs.outputs.published }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "pnpm"

      - run: pnpm install --no-frozen-lockfile

      - name: Package
        run: pnpm package

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Print Changesets Outputs
        run: echo "${{ toJson(steps.changesets.outputs) }}"

      - id: printoutputs
        ##if has changeset build and deploy
        run: echo "published=${{ steps.changesets.outputs.hasChangesets }}" >> "$GITHUB_OUTPUT"

      - name: Build
        if: ${{ steps.changesets.outputs.hasChangesets == 'true' }}
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: pnpm build

      - name: Upload Artifacts
        if: ${{ steps.changesets.outputs.hasChangesets == 'true' }}
        uses: actions/upload-pages-artifact@v2
        with:
          path: "apps/documentation/build/"

  deploy:
    if: ${{ needs.release.outputs.published == 'true' }}
    name: Documentation Deployment
    needs: release
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
